import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";
import "./globals.css";
import Navbar from "@/Components/Header/Navbar";
import LenisWrapper from "@/Components/Wrappers/LenisWrapper";
import { Sigmar } from "next/font/google";

const sigmar = Sigmar({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`${sigmar.className}  antialiased`}>
          <LenisWrapper>
            <Navbar />
            {children}
          </LenisWrapper>
        </body>
      </html>
    </ViewTransitions>
  );
}
